doc/source/skqulacs.circuit.rst
doc/source/skqulacs.rst
skqulacs/circuit.py
skqulacs/qnn/classifier.py
skqulacs/qnn/qnnbase.py
skqulacs/qnn/regressor.py
tests/test_circuit.py
tests/test_qnn_regressor.py

closes: #31 
量子回路クラスを実装しました．いまはまだ regressor しか対応していません．
多次元の入力データをエンコードする処理はユーザが書くようにしていますがこのクラスに組み込むべきでしょうか?
https://github.com/Qulacs-Osaka/scikit-qulacs/blob/f8cbccc1485cf260ed875c334f1109a597030b2f/tests/test_qnn_regressor.py#L11-L21

learning circuit

---

requirements-dev.txt
skqulacs/qnn/classifier.py
skqulacs/qnn/regressor.py
skqulacs/typing.py

Move "import Literal" to another file

---

.github/workflows/doc.yml
.github/workflows/unittest.yml

Python 3.7~3.9 で CI を回すようにしました．

Multiple Python version CI

---

skqulacs/circuit/circuit.py

fix _add_R_gate_inner

---

skqulacs/circuit/pre_defined.py
skqulacs/qnn/regressor.py
tests/test_qnn_regressor.py
tests/test_qnn_regressor_farhi.py

BFGS追加。　BFGSでtestした。

---

Makefile
skqulacs/circuit/pre_defined.py
skqulacs/qnn/classifier.py
skqulacs/qnn/regressor.py
tests/test_qnn_classifier.py
tests/test_qnn_regressor.py
tests/test_qnn_regressor_farhi.py
tests/test_qsvm_classifier.py
tests/test_qsvm_regressor.py

Use `LearningCircuit` in classifier

---

skqulacs/circuit/__init__.py
skqulacs/circuit/graph.py
tests/graph_bloch.py

これでいいのかはよくわからない。
test_ではじまってないファイル名にしたら、自動テストが走らないので、
matplotのテストを入れてもいい

ブロッホ球の3D表示をした。

---

CONTRIBUTING-en.md
CONTRIBUTING-ja.md
requirements-dev.txt

close #58 
CONTRIBUTING のコマンド例の修正

fix command doc

---

.github/workflows/unittest.yml
skqulacs/qnn/classifier.py
skqulacs/qnn/qnnbase.py
skqulacs/qnn/regressor.py
tests/test_qnn_classifier.py

Boost を CI 上でインストールして qulacs-osaka をビルドできるようにしました．
qulacs-osaka が PyPI にアップロードされるまでのワークアラウンドです．

Build qulacs osaka in ci

---

.github/workflows/doc.yml

[Fix] :bug: add boost-install step to doc.yml

---

.github/workflows/doc.yml
.github/workflows/unittest.yml
.github/workflows/wheel.yml

close #109
- Set up wheel build CI
- Delete boost from doc CI (#113)

CI to upload to PyPI

---

doc/source/notebooks/0_tutorial.ipynb
skqulacs/qnn/classifier.py
skqulacs/qnn/regressor.py
tests/test_qnn_classifier.py
tests/test_qnn_regressor.py
tests/test_qnn_regressor_farhi.py

close #117 
QNNClassifier と QNNRegressor クラスのn_qubitはLearningCircuitに情報があるため、引数から削除した。
また、全角スペースが何か所かあったので半角スペースに変更した。
あまり自信がないので、指摘お願いします。

LearningCircuitからn_qubitを受け取るように変更。

---

.devcontainer/devcontainer.json

close #120 
#120 での議論の通り，.venv のみを volume mount するようにしました．
体感でいいので，`poetry install` が速くなっていることを確認してもらえるとありがたいです．

Use volume mount for .venv

---

.github/workflows/doc.yml

`--no-root` があると doc/source/notebooks/0_example.ipynb で skqulacs を import できなかった(実行はできていたらしいです 🤔 )ので外しました．
ガッとやったのでまずいところがあったら指摘お願いします 🙏 
問題なさそうなら approve と同時にマージしてもらって構わないです

Remove --no-root to install skqulacs to venv for doc build

---

skqulacs/circuit/circuit.py
skqulacs/circuit/pre_defined.py
skqulacs/qnn/classifier.py
skqulacs/qnn/qnnbase.py
skqulacs/qnn/regressor.py
skqulacs/qsvm/qsvc.py
skqulacs/qsvm/qsvr.py
tests/test_qnn_classifier.py
tests/test_qnn_regressor.py
tests/test_qnn_regressor_farhi.py
tests/test_qsvm_regressor.py
tests/test_qsvm_regressor_deep.py
tests/test_qsvm_regressor_npqc_yzcx.py

close #136 
動作を変えるような変更はしていません．修整漏れがあったら教えてください．
コードを眺めていて，入出力のスケーリング，コスト関数，ソルバはクラスとして切り出した方が見通しがよくなると思いました．
特にスケーリングのコードが重複しており意図が読み取りにくい状態なので，そこから取り掛かるのがよさそうです．

Clean up code

---

skqulacs/circuit/circuit.py

close #162 
* `_Parameter` を `_LearningParameter` と `_InputParameter` に分離しました．
* LearningCircuit の構造について docstring で補足しました

Refactor `LearningCircuit`

---

skqulacs/qnn/classifier.py
skqulacs/qnn/regressor.py
tests/test_qnn_classifier.py
tests/test_qnn_regressor.py

early_stopping

---

.github/workflows/unittest.yml

close #175 
`python-version: [3.7, 3.8, 3.9, 3.10]` とすると 3.10 が 3.1 と認識されたので quote する必要がありました．

Run unittest on Python 3.10

---

skqulacs/circuit/circuit.py
tests/test_circuit.py

_PositionDetail クラスを追加して、positions_in_circuit で、共有パラメータの位置と係数を管理するようにしました。
パラメータとしては共有されているので、実行した結果で、係数のテストをしました。

#169: 共有されているパラメータに係数をかけられるようにする

---

skqulacs/circuit/circuit.py

`backprop_inner_product` が #195 の変更に対応できていなかったので修正しました．

Fix impl that should have been done in #195

---

skqulacs/circuit/pre_defined.py
tests/test_circuit.py
tests/test_qnn_generator.py

Specify default seed value of ansatzes as 0

---

skqulacs/qnn/classifier.py
skqulacs/qnn/regressor.py
tests/test_qnn_regressor.py

close #202 
- 2次元の出力の回帰をテストするようにした
- `QNNRegressor._cost_func_grad()` で `add_operator()` に `f"Z {i}"` を渡すように修正
- `QNNRegressor._cost_func_grad()` の2回目の `update_quantum_state()` の呼び出しは不要なため削除

Multi value regression

---

doc/source/skqulacs.rst
doc/source/skqulacs.save.rst
pyproject.toml

Release v0.4.0

---

poetry.lock
pyproject.toml

Release v0.4.1

---

tests/test_qnn_regressor_grad_descent.py

Not sure why since I am using seeds on generators, but when merged the network achieved 0.046 RMSE and my assert was <0.045, so now is a larger margin and should run without error

Modified assert to finish PR #254 successfully

---

skqulacs/qkrr/qkrr.py

predict by fitted model
